summary: ''
value:
  fullscreen: false
  grid:
    - '12':
        fixed: false
        fullHeight: false
        h: 2
        w: 12
        x: 0
        y: 0
      '3':
        fixed: false
        fullHeight: false
        h: 2
        w: 6
        x: 0
        y: 0
      id: a
      data:
        id: a
        type: containercomponent
        actions: []
        configuration: {}
        customCss:
          container:
            class: '!p-0'
            style: ''
        numberOfSubgrids: 1
    - '12':
        fixed: false
        fullHeight: false
        h: 12
        w: 8
        x: 0
        y: 2
      '3':
        fixed: false
        fullHeight: false
        h: 8
        w: 3
        x: 0
        y: 2
      id: d
      data:
        id: d
        type: schemaformcomponent
        actions: []
        componentInput:
          type: static
          value:
            order:
              - first_name
            properties:
              first_name:
                type: object
                default: {}
                format: resource-gmail
            required: []
          fieldType: schema
        configuration:
          defaultValues:
            type: static
            value: {}
          displayType:
            type: static
            value: false
          dynamicEnums:
            type: static
            value: {}
          largeGap:
            type: static
            value: false
        customCss:
          description:
            class: ''
            style: ''
          container:
            class: ''
            style: ''
          label:
            class: ''
            style: ''
  hiddenInlineScripts: []
  hideLegacyTopBar: true
  norefreshbar: false
  subgrids:
    a-0:
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          y: 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 0
          y: 0
        id: b
        data:
          id: b
          type: textcomponent
          actions: []
          componentInput:
            type: templatev2
            connections:
              - id: summary
                componentId: ctx
            eval: '${ctx.summary}'
            fieldType: template
          configuration:
            copyButton:
              type: static
              value: false
            disableNoText:
              type: static
              value: true
              fieldType: boolean
            style:
              type: static
              value: Body
            tooltip:
              type: evalv2
              value: ''
              connections:
                - id: author
                  componentId: ctx
              expr: '`Author: ${ctx.author}`'
              fieldType: text
          customCss:
            container:
              class: ''
              style: ''
            text:
              class: text-xl font-semibold whitespace-nowrap truncate
              style: ''
          horizontalAlignment: left
          verticalAlignment: center
      - '12':
          fixed: false
          fullHeight: false
          h: 1
          w: 6
          x: 6
          y: 0
        '3':
          fixed: false
          fullHeight: false
          h: 1
          w: 3
          x: 0
          y: 1
        id: c
        data:
          id: c
          type: recomputeallcomponent
          actions: []
          configuration: {}
          customCss:
            container:
              class: ''
              style: ''
          horizontalAlignment: right
          menuItems: []
          verticalAlignment: center
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: publisher
  triggerables_v2: {}
