summary: ''
value:
  fullscreen: false
  grid: []
  hiddenInlineScripts: []
  norefreshbar: false
  theme:
    type: path
    path: f/app_themes/theme_0
  unusedInlineScripts: []
policy:
  execution_mode: publisher
  triggerables_v2: {}
